import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import DropImageCard from '@/components/DropImageCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dynamic Background</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles['header-container']}>
          <h1>Dynamic Background</h1>
          <p>Drop your image in the box below to add a dynamic background to it</p>
        </section>
        <section className={styles['drop-image-card-container']}>
          <DropImageCard />
        </section>
      </main>
    </>
  )
}
